### ISSUE TITLE
Dialog, Menu, DatePicker not working well with server rendering

### ISSUE THREAD

**Issue by skylinezum** [ofzza/react-toolbox-build4server#1]
Hi,

I am using build4server in an isomorphic web app and i have an issue when opening dialogs and menu and datepicker and tooltip is not working properly. On client only builds with vanilla toolbox, it works fine, but I am using this to solve a server rendering build.

A common error is on ripples for button clicks. It creates these errors:
`admin.js:56492 Uncaught TypeError: Cannot read property 'parentNode' of null`

I believe it's because multiple react copies are being loaded, but I'm wondering if this is something that's happened before.

Thanks for working on this package and keep up the good work!

**Comment by ofzza** [comment]
I can't say I've seen this error before ...

Can you please post more info on how this happens (your build procedure, package.json dependencies, etc ...), ideally post or email me a sample project? 
What exactly makes you think the problem is in loading multiple _react_ instances?

When you say "On client only builds with vanilla toolbox" - do you mean to say that you're using vanilla _react-toolbox_ for client-side rendering and _react-toolbox-build4server_ on server-side, all in the same project? ... or are you saying you tried vanilla _react-toolbox_on client-side and it didn't have the same issues?

**Comment by skylinezum** [comment]
Hi, thanks for replying and sorry for taking so long. so I used vanilla react-toolbox in a client-side rendered project separate from the project using build4server. I had no issues with it, but when using build4server in the current project, I get all these issues.

So this server side project is using gulp to process the styling and also start webpack.

I've emailed you a sample project. Let me know if you have any questions about that sample project.

**Comment by ofzza** [comment]
The problem you're having doesn't really have much to do with react-toolbox-build4server, but with your webpack task.
Since you're including a client-side react library directly, you should keep all of react and react addons out of the client-side build, which your gulp webpack task wasn't doing properly ...

What you need (only for your client-side build) is a correct exclusion declaration in webpack configuration:

``` js
var wconfig = {
  ...
   externals: {
      'React': 'React',
      'react': 'React',
      'ReactDOM': 'ReactDOM',
      'react-dom': 'ReactDOM',
      'react-addons-css-transition-group': 'React.addons.CSSTransitionGroup',
   }
  ...
};
```

Then when you include the client-side react library with `<script src=" ... "></script>` you don't end up with a doubled React instance and things work.

Also, if you want React to be able to just take over from your server-side render, make sure you're using the same version of React on both server-side and client-side.

**Comment by skylinezum** [comment]
Thanks for pointing this out to me, I believe this then is off topic for this issue and I will email you for issues pertaining to webpack
